# mkdir ~/code ~/code/{checkouts,repos} on given server(s)

- hosts: "{{ hosts }}"

  vars:
    user: ubuntu
    remote_user_home: /home/{{ user }}

  tasks:
  - name: mkdir ~/code ~/code/{checkouts,repos}
    file: >
      path={{ remote_user_home }}/{{ item }}
      state=directory
      owner={{ user }}
      group={{ user }}
      mode=0775
    with_items:
    - code
    - code/repos
    - code/checkouts
