# Creates user and adds it to sudoers. Run with
#   ansible-playbook create_sudo_user.yml -e 'hosts=do1 user=ubuntu password=s3cr3tp4ss'
# Assumes that openssl is installed on the hosts

- hosts: "{{ hosts }}"
  remote_user: root

  vars:
    user: ubuntu
    remote_user_home: /home/{{ user }}

  tasks:
  - name: Create user account
    shell: useradd -m -r -U -p `openssl passwd {{ password }}` -s /bin/bash -d /home/{{ user }} {{ user }}

- include: make_user_sudoer.yml hosts={{ hosts }} user={{ user }}
