# Install Python-related packages to given server(s)
#   ansible-playbook install_base_packages.yml -e hosts=do1

- hosts: {{ hosts }}

  tasks:
  - name: Install Python packages via apt
    apt: pkg={{ item }} state=present
    with_items:
    - ipython
    - python-dev
    - python-distutils-extra
    - python-pip
    - python-setuptools

  - name: Install Python packages via pip
    pip: name={{ item }} state=present
    with_items:
    - virtualenv
    - virtualenvwrapper
