# Install base packages to new server. Run with
#   ansible-playbook install_postgres.yml -e hosts=do1

- hosts: "{{ hosts }}"

  tasks:
  - name: Install Postgres
    apt: pkg={{ item }} state=present
    with_items:
    - postgresql-client
    - postgresql-server-dev-all
    - postgresql-9.3
