# Install base packages to new server. Run with
#   ansible-playbook install_apache_postgres.yml -e hosts=do1

- include: install_apache.yml   hosts={{ hosts }}
- include: install_postgres.yml hosts={{ hosts }}
