# Install base packages to new server. Run with
#   ansible-playbook install_base_packages.yml -e hosts=do1

- hosts: {{ hosts }}

  tasks:
  - name: install base packages
    apt: pkg={{ item }} state=present
    with_items:
    - curl
    - emacs23
    - gcc
    - git-core
    - htop
    - lynx
    - make
    - mtr
    - netcat-traditional
    - nmap
    - screen
    - unzip
    - whois
