# Create new deployable git repo on server. Run with something like
#   ansible-playbook new_deployable_git_repo.yml -e 'hosts=do1 project_name=syndicate_pro'

- hosts: "{{ hosts }}"

  vars:
    user: ubuntu
    remote_user_home: /home/{{ user }}

  tasks:
  - name: create bare git repo and containing directory
    command: git init --bare {{ remote_user_home }}/code/repos/{{ project_name }}

  - name: mkdir -p ~/code/checkouts/$project_name
    file: >
      path={{ remote_user_home }}/code/checkouts/{{ project_name }}
      state=directory
      owner={{ user }}
      group={{ user }}
      mode=0775

  - name: cp post-receive $project_name/hooks/post-receive
    command: cp {{ remote_user_home }}/code/post-receive {{ remote_user_home }}/code/repos/{{ project_name }}/hooks/
