# Create new deployable git repo on server. Run with something like
#   ansible-playbook -e 'hosts=do1 project_name=syndicate_pro'

- hosts: {{ hosts }}
  remote_user: ubuntu
  vars:
    remote_user_home: /home/ubuntu
  tasks:
  - name: create bare git repo and containing directory
    command: git init --bare {{ remote_user_home }}/code/repos/{{ project_name }}

  - name: mkdir -p ~/code/checkouts/$project_name
    file: path={{ remote_user_home }}/code/checkouts/{{ project_name }} state=directory

  - name: cp post-receive $project_name/hooks/post-receive
    command: cp {{ remote_user_home }}/code/post-receive {{ remote_user_home }}/code/repos/{{ project_name }}/hooks/
