# Makes user a sudoer if s/he isn't already, then grants him/her
# permission to do passwordless sudo. Run with something like
#
#   ansible-playbook pwless_sudo.yml -e 'hosts=do1 user=ubuntu'

- include: make_user_sudoer.yml hosts={{ hosts }} user={{ user }}

- hosts: "{{ hosts }}"
  sudo: true

  vars:
    user: ubuntu

  tasks:
  - name: Enable passwordless sudo for given user
    lineinfile: >
      dest=/etc/sudoers
      backrefs=true
      regexp='{{ user }}	ALL=\(ALL:ALL\) ALL'
      line='{{ user }}	ALL=(ALL) NOPASSWD:ALL'
      state=present
